os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "nightly"
  - "pypy3"
env: TOXENV=py,codecov

matrix:
  include:
    - dist: xenial
      sudo: required
      python: "3.7"
    - env: TOXENV=stylecheck,docs-html
    - os: osx
      language: generic
      env: TOXENV=py3,py2,codecov
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip
  allow_failures:
    - python: nightly
    - python: pypy3
    - os: osx
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      brew install python@2
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi

install:
  - pip install -U tox

script:
  - tox --skip-missing-interpreters false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master
    - /^\d+(\.\d+)*(\.x|-maintenance)?$/

notifications:
  email: false
